name: pipeline
channels:
  - anaconda
  - cyclus
  - conda-forge
  - bioconda
  - nodefaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - biopython=1.84
  - blast=2.16.0
  - blosc=1.21.6
  - bowtie2=2.5.4
  - bzip2=1.0.8
  - c-ares=1.34.2
  - c-blosc2=2.15.2
  - ca-certificates=2024.12.14
  - curl=8.11.1
  - dill=0.3.9
  - entrez-direct=22.4
  - fastp=0.24.0
  - fastq-pair=1.0
  - gettext=0.22.5
  - gettext-tools=0.22.5
  - hdf5=1.14.3
  - htslib=1.21
  - isa-l=2.31.0
  - java-jdk=8.45.14
  - keyutils=1.6.1
  - krb5=1.21.3
  - ld_impl_linux-64=2.43
  - libaec=1.1.3
  - libasprintf=0.22.5
  - libasprintf-devel=0.22.5
  - libblas=3.9.0
  - libcblas=3.9.0
  - libcurl=8.11.1
  - libdeflate=1.22
  - libedit=3.1.20191231
  - libev=4.33
  - libffi=3.4.2
  - libgcc=14.2.0
  - libgcc-ng=14.2.0
  - libgettextpo=0.22.5
  - libgettextpo-devel=0.22.5
  - libgfortran=14.2.0
  - libgfortran-ng=14.2.0
  - libgfortran5=14.2.0
  - libgomp=14.2.0
  - libidn2=2.3.7
  - liblapack=3.9.0
  - liblzma=5.6.3
  - libnghttp2=1.64.0
  - libnsl=2.0.1
  - libopenblas=0.3.28
  - libsqlite=3.47.2
  - libssh2=1.11.1
  - libstdcxx=14.2.0
  - libstdcxx-ng=14.2.0
  - libunistring=0.9.10
  - libuuid=2.38.1
  - libxcrypt=4.4.36
  - libzlib=1.3.1
  - lz4-c=1.10.0
  - lzo=2.10
  - multiprocess=0.70.15
  - ncbi-vdb=3.1.1
  - ncurses=6.5
  - nomkl=1.0
  - numexpr=2.10.2
  - numpy=1.26.4
  - openssl=3.4.0
  - packaging=24.2
  - pandarallel=1.6.5
  - pandas=2.2.3
  - perl=5.32.1
  - perl-archive-tar=2.40
  - perl-carp=1.50
  - perl-common-sense=3.75
  - perl-compress-raw-bzip2=2.201
  - perl-compress-raw-zlib=2.202
  - perl-encode=3.21
  - perl-exporter=5.74
  - perl-exporter-tiny=1.002002
  - perl-extutils-makemaker=7.70
  - perl-io-compress=2.201
  - perl-io-zlib=1.14
  - perl-json=4.10
  - perl-json-xs=4.03
  - perl-list-moreutils=0.430
  - perl-list-moreutils-xs=0.430
  - perl-parent=0.242
  - perl-pathtools=3.75
  - perl-scalar-list-utils=1.63
  - perl-storable=3.15
  - perl-types-serialiser=1.01
  - pip=24.2
  - psutil=6.1.0
  - py-cpuinfo=9.0.0
  - pysam=0.22.1
  - pytables=3.9.2
  - python=3.9.19
  - python-dateutil=2.9.0
  - python-tzdata=2024.2
  - python_abi=3.9
  - pytz=2024.1
  - readline=8.2
  - rpsbproc=0.5.0
  - samtools=1.21
  - seqkit=2.9.0
  - setuptools=75.1.0
  - six=1.16.0
  - snappy=1.2.1
  - starcode=1.4
  - tk=8.6.13
  - tzdata=2024b
  - vsearch=2.29.1
  - wget=1.21.4
  - wheel=0.44.0
  - xz=5.2.6
  - zlib=1.3.1
  - zlib-ng=2.2.2
  - zstd=1.5.6
